# Generated by Django 4.0 on 2021-12-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('identificacion', models.IntegerField(unique=True, verbose_name='Cedula')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('correo', models.EmailField(max_length=100, verbose_name='correo')),
                ('telefono', models.CharField(max_length=30, verbose_name='telfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre_de_categoría')),
            ],
        ),
        migrations.CreateModel(
            name='CentroDeAcopio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre_del_centro_de_acopio')),
                ('zona', models.CharField(max_length=50, verbose_name='Zona')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=50, verbose_name='Encargado')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_centroacopio', to='reciclApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reciclador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=50, verbose_name='Zona')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciclador_categoria', to='reciclApp.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='reciclApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, max_length=50, verbose_name='Fecha')),
                ('centro_de_acopio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centro_acopio_solicitud', to='reciclApp.centrodeacopio')),
                ('reciclador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciclador_solicitud', to='reciclApp.reciclador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_solicitud', to='reciclApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20, verbose_name='estado')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre de categoría')),
                ('imagen', models.CharField(max_length=300, verbose_name='URL_imagen')),
                ('peso', models.IntegerField(default=0, verbose_name='peso')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('disponible', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino_producto', to='reciclApp.usuario')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_producto', to='reciclApp.usuario')),
            ],
        ),
    ]
