# Generated by Django 4.0 on 2021-12-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciclApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodeacopio',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centroacopio', to='reciclApp.usuario'),
        ),
        migrations.AlterField(
            model_name='reciclador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciclador', to='reciclApp.usuario'),
        ),
    ]
